# Generated by Django 4.0.6 on 2022-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.CharField(max_length=10)),
                ('pizzaPrice', models.CharField(max_length=10)),
            ],
        ),
    ]
