# Generated by Django 4.0.6 on 2022-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDeliveryApp', '0002_customermodel_alter_pizzamodel_pizzaname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzasOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerUsername', models.CharField(max_length=10)),
                ('customerContactNumber', models.CharField(max_length=10)),
                ('customerAddress', models.CharField(max_length=10)),
                ('PizzasOrderedItems', models.CharField(max_length=10)),
                ('customerStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
